### ISSUE TITLE
Update dependencies for the academic year 2024-25

### ISSUE THREAD

**Issue by ccamara** [WarwickCIM/IM939_handbook#9]
From https://github.com/WarwickCIM/IM939_handbook/blob/main/README_setup.md:

> This project, uses a conda environment called `IM939`, which will install all the packages and versions (as well as their dependencies) as defined in the file `environment.yml` at the root of this project.

## Task

[`environment.yml`](https://github.com/WarwickCIM/IM939_handbook/blob/main/environment.yml) contains the dependencies used for this project. Its current content reflects the working versions at September 2023, and therefore, they will need to be updated to newer versions.

To do so, you will need to:

- [x] Update [`environment.yml`](https://github.com/WarwickCIM/IM939_handbook/blob/main/environment.yml) with newer versions
- [x] Check that the new versions do not trigger errors or warnings:
   - [x] Render the handbook to check whether warnings or errors (see https://github.com/WarwickCIM/IM939_handbook/blob/main/README_setup.md#recreating-the-handbook)
   - [x] Make adjustments to the offending code to address any error or warning
- [x] Deploy the handbook to github pages: https://github.com/WarwickCIM/IM939_handbook/blob/main/README_setup.md#recreating-the-handbook

## References:

* Environment's configuration for this project: https://github.com/WarwickCIM/IM939_handbook/blob/main/README_setup.md#setting-up-the-environment
* https://stackoverflow.com/questions/57701571/what-is-the-right-way-to-update-anaconda-and-conda-base-environments

**Comment by ccamara** [comment]
Hi @eshasadia , thanks for updating the dependencies file. Could you please check that the code in every notebook does not trigger any warnings or errors due to deprecated code/syntax? I'm quite confident that some libraries have changed some parameters and may now yield deprecation notices or even errors. We should be able to detect them before students find out during teaching.

If you tried to regenerate the handbook using `quarto render` after recreating the environment, you may want to know that the code cells of previously ran notebooks (actually, every notebook) would have not been run because they were already rendered, and their status was frozen to avoid having to be recreated every time. (see https://quarto.org/docs/projects/code-execution.html). To make sure that the code cells are actually run, you will need to run `quarto render --cache-refresh` as described https://github.com/WarwickCIM/IM939_handbook/blob/main/README_setup.md#recreating-the-handbook. 

Also, do not forget to deploy the handbook after making sure that it works locally.

I'm reopening this issue until you make sure there are no warnings/errors. Let me know if you need further assistance.

**Comment by eshasadia** [comment]
Hi, I have deployed the handbook to GitHub pages, can you please have a look if everything is fine, then i'll close this issue

**Comment by ccamara** [comment]
Hi Esha,

I can confirm I can't see any warning or error in the deployed site.
I can confirm that this local test didn't produce any other warning either:

1. pulled the main branch, 
2. recreated the environment IM939
3. deleted the `_freeze/` folder to make sure that all notebooks were recreated
4. run `quarto render` to regenerate the handbooks and populate the `_freeze` folder again.
5. run `quarto preview` to see changes locally in real time

I didn't find anything worth fixing, besides some formatting issues that I addressed here [b818b84](https://github.com/WarwickCIM/IM939_handbook/commit/b818b84edd7f0e84513c9f3ce46bd8e369bdeb6b)
